apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-dynamo-cleaner
  namespace: wiseling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversion-dynamo-cleaner
  template:
    metadata:
      labels:
        app: conversion-dynamo-cleaner
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: conversion-dynamo-cleaner
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: conversion-dynamo-cleaner
            topologyKey: kubernetes.io/hostname
      containers:
      - name: conversion-dynamo-cleaner
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/conversion-service:1.2.0
        command: ["python", "-m", "app.services.dynamo_cleaner"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-conversion
                key: DATABASE_URL
        resources:
          limits:
            memory: "192Mi"
            cpu: "100m"
          requests:
            memory: "96Mi"
            cpu: "50m"