apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdrawal-processor
  namespace: wiseling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: withdrawal-processor
  template:
    metadata:
      labels:
        app: withdrawal-processor
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: withdrawal-processor
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: withdrawal-processor
              topologyKey: kubernetes.io/hostname
      containers:
      - name: withdrawal-processor
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/withdrawal-service:1.2.0
        command: ["python", "-m", "app.services.outbox_poller"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-withdrawal
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "150m"
          requests:
            memory: "128Mi"
            cpu: "50m"