apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-outbox-poller
  namespace: wiseling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversion-outbox-poller
      deployment: green
  template:
    metadata:
      labels:
        app: conversion-outbox-poller
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: conversion-outbox-poller
      containers:
      - name: conversion-outbox-poller
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/conversion-service:1.0.9
        command: ["python", "-m", "app.services.outbox_poller"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-conversion
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "150m"
          requests:
            memory: "128Mi"
            cpu: "50m"