apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-consumer
  namespace: wiseling
  matchLabels:
    app: wallet-consumer
    deployment: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-consumer
      deployment: green
  template:
    metadata:
      labels:
        app: wallet-consumer
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      containers:
      - name: wallet-consumer
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/wallet-service:1.0.13
        command: ["python", "-m", "app.services.consumer"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-wallet
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"