apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdrawal-dynamo-cleaner
  namespace: wiseling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: withdrawal-dynamo-cleaner
      deployment: green
  template:
    metadata:
      labels:
        app: withdrawal-dynamo-cleaner
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      containers:
      - name: withdrawal-dynamo-cleaner
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/withdrawal-service:1.0.14
        command: ["python", "-m", "app.services.dynamo_cleaner"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-withdrawal
                key: DATABASE_URL
        resources:
          limits:
            memory: "192Mi"
            cpu: "100m"
          requests:
            memory: "96Mi"
            cpu: "50m"