apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdrawal-processor
  namespace: wiseling
  labels:
    deployment: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: withdrawal-processor
      deployment: green
  template:
    metadata:
      labels:
        app: withdrawal-processor
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      containers:
      - name: withdrawal-processor
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/withdrawal-service:1.0.15
        command: ["python", "-m", "app.services.processor"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-withdrawal
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "150m"
          requests:
            memory: "128Mi"
            cpu: "50m"