apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-service-deployment
  namespace: wiseling
  labels:
    app: conversion-service
    deployment: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversion-service
      deployment: green
  template:
    metadata:
      labels:
        app: conversion-service
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: conversion-service
      containers:
      - name: conversion-service
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/conversion-service:1.0.9
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: wiseling-config
        - secretRef:
            name: jwt-secret
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-url-conversion
              key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "50m"