apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: conversion-service-latency
  namespace: wiseling
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - wiseling
    labelSelectors:
      app: conversion-service
  delay:
    latency: "3000ms"
    correlation: "100"
    jitter: "0ms"
  duration: "2m"