# Redis Master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: wiseling
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: redis-replica
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "no", "--save", ""]
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
          requests:
            memory: "64Mi"
            cpu: "50m"
---
# Redis Replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  namespace: wiseling
  labels:
    app: redis-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: redis-master
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server", "--replicaof", "redis-master", "6379", "--appendonly", "no", "--save", ""]
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
          requests:
            memory: "64Mi"
            cpu: "50m"
---
# Redis master svc
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: wiseling
spec:
  selector:
    app: redis-master
  ports:
  - port: 6379
    targetPort: 6379
---
# Redis replica svc
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: wiseling
spec:
  selector:
    app: redis-replica
  ports:
  - port: 6379
    targetPort: 6379