apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-consumer
  namespace: wiseling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-consumer
      deployment: green
  template:
    metadata:
      labels:
        app: wallet-consumer
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: wallet-consumer
      containers:
      - name: wallet-consumer
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/wallet-service:1.2.0
        command: ["python", "-m", "app.services.consumer"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-wallet
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "150m"
          requests:
            memory: "128Mi"
            cpu: "50m"