apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-outbox-poller
  namespace: wiseling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversion-outbox-poller
  template:
    metadata:
      labels:
        app: conversion-outbox-poller
    spec:
      serviceAccountName: wiseling-sa
      containers:
      - name: conversion-outbox-poller
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/conversion-service:1.0.4
        command: ["python", "-m", "app.services.outbox_poller"]
        envFrom:
          - configMapRef:
              name: wiseling-config
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-conversion
                key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"