apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deployment
  namespace: wiseling
  labels:
    app: wallet-service
    deployment: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
      deployment: green
  template:
    metadata:
      labels:
        app: wallet-service
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: wallet-service
      containers:
      - name: wallet-service
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/wallet-service:1.0.16
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: wiseling-config
        - secretRef:
            name: jwt-secret
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-url-wallet
              key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"