apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-service-deployment
  namespace: wiseling
  labels:
    app: conversion-service
    deployment: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversion-service
      deployment: green
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
      labels:
        app: conversion-service
        deployment: green
    spec:
      serviceAccountName: wiseling-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: conversion-service
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: conversion-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: conversion-service
        image: 359707702022.dkr.ecr.ap-southeast-2.amazonaws.com/wiseling/conversion-service:1.2.0
        ports:
        - containerPort: 8002
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 10
        envFrom:
        - configMapRef:
            name: wiseling-config
        - secretRef:
            name: jwt-secret
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-url-conversion
              key: DATABASE_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"